### ISSUE TITLE
io.appmetrica.analytics.ValidationException: AppMetrica isn't initialized. Use AppMetrica#activate(android.content.Context, String) method to activate.

### ISSUE THREAD

**Issue by ashishmistry416** [appmetrica/appmetrica-react-native-plugin#3]
App is crashing with release build in android. All setup same as given but still crashing. in debug working fine.

Here is my project package versions:
"@appmetrica/react-native-analytics": "^3.1.0",
"react": "18.1.0",
"react-native": "0.70.0",

Here is exact issue from android studio logcat:
FATAL EXCEPTION: mqt_native_modules
Process: com.tbs.uae, PID: 27510
io.appmetrica.analytics.ValidationException: AppMetrica isn't initialized. Use AppMetrica#activate(android.content.Context, String) method to activate.
at io.appmetrica.analytics.impl.qm.a(SourceFile:5)
at io.appmetrica.analytics.impl.j1.b(SourceFile:7)
at io.appmetrica.analytics.AppMetrica.reportEvent(SourceFile:2)
at io.appmetrica.analytics.reactnative.AppMetricaModule.reportEvent(AppMetricaModule.java:80)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
at java.lang.Thread.run(Thread.java:1012)

**Comment by HessiPard** [comment]
> App is crashing with release build in android. All setup same as given but still crashing. in debug working fine.
> 
> Here is my project package versions: "@appmetrica/react-native-analytics": "^3.1.0", "react": "18.1.0", "react-native": "0.70.0",
> 
> Here is exact issue from android studio logcat: FATAL EXCEPTION: mqt_native_modules Process: com.tbs.uae, PID: 27510 io.appmetrica.analytics.ValidationException: AppMetrica isn't initialized. Use AppMetrica#activate(android.content.Context, String) method to activate. at io.appmetrica.analytics.impl.qm.a(SourceFile:5) at io.appmetrica.analytics.impl.j1.b(SourceFile:7) at io.appmetrica.analytics.AppMetrica.reportEvent(SourceFile:2) at io.appmetrica.analytics.reactnative.AppMetricaModule.reportEvent(AppMetricaModule.java:80) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) at com.facebook.jni.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) at java.lang.Thread.run(Thread.java:1012)

same issue here

**Comment by ziqq** [comment]
I have this same issue, but i use `flutter`

**Comment by HessiPard** [comment]
Just resolved the issue.
We just didn't initialize the sdk in some cases in our app (for example in 'fr' language) and in case of sending event report, sdk crashed!

**Comment by NesterovichAlexey** [comment]
If the problem is still unresolved, please contact customer support at https://appmetrica.yandex.com/docs/troubleshooting/feedback-new . Please attach a sample on which this problem is reproduced.
